import { Shape, Mesh, Math, Vector3, CanvasTexture } from 'three'
import geometry from '../geometry'
import material from '../material'
import { getPosition } from '../utils'
import { boxMarkAnimate } from '../animation'
import _ from 'lodash'
